# Generated by Django 5.1.4 on 2026-08-23 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('syllabus', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MasteryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct', models.BooleanField()),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('hints_used', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('objective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='syllabus.learningobjective')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mastery_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Mastery events',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='MasteryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mastery', models.FloatField(default=0.3)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('correct_count', models.PositiveIntegerField(default=0)),
                ('last_reviewed_at', models.DateTimeField(auto_now=True)),
                ('objective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mastery_records', to='syllabus.learningobjective')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mastery_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('student', 'objective')},
            },
        ),
    ]
