# Generated by Django 5.1.4 on 2026-09-01 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0001_initial'),
        ('syllabus', '0007_learningobjective_code_topic_code_topic_kind_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='masteryrecord',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mastery_records', to='syllabus.subject'),
        ),
        migrations.AddIndex(
            model_name='masteryrecord',
            index=models.Index(fields=['student', 'subject', 'mastery'], name='progress_ma_student_12f558_idx'),
        ),
    ]
