# Generated by Django 5.1.4 on 2026-08-24 20:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
        ('syllabus', '0003_syllabusdocument_doc_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='answer_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='awarded_marks',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='adapted_from_past_paper',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='format',
            field=models.CharField(choices=[('mcq', 'Multiple choice'), ('structured', 'Structured / free response')], default='mcq', max_length=12),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='marking_guidance',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='marks',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='paper_label',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='source_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='selected_index',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='correct_index',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='options',
            field=models.JSONField(default=list),
        ),
        migrations.CreateModel(
            name='ExamSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_number', models.PositiveSmallIntegerField(default=1)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('total_questions', models.PositiveSmallIntegerField(default=0)),
                ('plan', models.JSONField(default=dict)),
                ('question_ids', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('in_progress', 'In progress'), ('completed', 'Completed')], default='in_progress', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_sessions', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_sessions', to='syllabus.subject')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ExamBlueprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_number', models.PositiveSmallIntegerField(default=1)),
                ('data', models.JSONField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blueprints', to='syllabus.subject')),
            ],
            options={
                'unique_together': {('subject', 'paper_number')},
            },
        ),
    ]
