# Generated by Django 5.1.4 on 2026-08-29 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_quizattempt_answer_text_quizattempt_awarded_marks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='source',
            field=models.CharField(blank=True, choices=[('igcse', 'Cambridge IGCSE'), ('egcse', 'Eswatini GCSE')], max_length=10),
        ),
    ]
