# Generated by Django 5.1.4 on 2026-08-30 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_quizquestion_source'),
        ('rag', '0002_documentchunk_page_number_documentfigure'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='figures',
            field=models.ManyToManyField(blank=True, related_name='questions', to='rag.documentfigure'),
        ),
    ]
