# Generated by Django 5.1.4 on 2026-09-05 09:21

import apps.quiz.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_quizquestion_figures'),
        ('syllabus', '0008_syllabusdocument_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionCrop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_number', models.CharField(max_length=10)),
                ('stable_key', models.CharField(blank=True, default='', max_length=140, unique=True)),
                ('pages', models.JSONField(default=list)),
                ('ocr_text', models.TextField(blank=True)),
                ('confidence', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('auto', 'Automatic'), ('needs_qc', 'Needs review'), ('approved', 'Approved')], default='auto', max_length=10)),
                ('correct_index', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('marking_guidance', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_crops', to='syllabus.syllabusdocument')),
            ],
            options={
                'ordering': ('document_id', 'q_number'),
            },
        ),
        migrations.CreateModel(
            name='QuestionCropImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.PositiveSmallIntegerField()),
                ('sort', models.PositiveSmallIntegerField(default=0)),
                ('image', models.ImageField(upload_to=apps.quiz.models.question_crop_upload_to)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='quiz.questioncrop')),
            ],
            options={
                'ordering': ('sort',),
            },
        ),
        migrations.AddConstraint(
            model_name='questioncrop',
            constraint=models.UniqueConstraint(fields=('document', 'q_number'), name='unique_crop_per_question'),
        ),
    ]
