# Generated by Django 5.1.4 on 2026-09-05 09:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_questioncrop_questioncropimage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='questioncrop',
            name='format',
            field=models.CharField(default='structured', max_length=12),
        ),
        migrations.AddField(
            model_name='questioncrop',
            name='marks',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='CropAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_index', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('answer_text', models.TextField(blank=True)),
                ('awarded_marks', models.FloatField(blank=True, null=True)),
                ('correct', models.BooleanField(default=False)),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='quiz.questioncrop')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crop_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
