# Generated by Django 5.1.4 on 2026-09-05 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_questioncrop_format_questioncrop_marks_cropattempt'),
        ('syllabus', '0008_syllabusdocument_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionAnchor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qid', models.CharField(max_length=10)),
                ('page_number', models.PositiveSmallIntegerField()),
                ('bbox', models.JSONField(default=list)),
                ('kind', models.CharField(default='text', max_length=10)),
                ('confidence', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('auto', 'Automatic'), ('needs_qc', 'Needs review'), ('approved', 'Approved')], default='auto', max_length=10)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anchors', to='syllabus.syllabusdocument')),
            ],
            options={
                'ordering': ('document_id', 'page_number', 'qid'),
                'constraints': [models.UniqueConstraint(fields=('document', 'qid'), name='unique_anchor_per_question')],
            },
        ),
    ]
