# Generated by Django 5.1.4 on 2026-09-05 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_questionanchor'),
        ('syllabus', '0008_syllabusdocument_session'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='questionanchor',
            name='unique_anchor_per_question',
        ),
        migrations.AddConstraint(
            model_name='questionanchor',
            constraint=models.UniqueConstraint(fields=('document', 'qid', 'page_number'), name='unique_anchor_per_question_page'),
        ),
    ]
