# Generated by Django 5.1.4 on 2026-09-05 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_questionanchor_correct_index_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paperattempt',
            name='drawing',
            field=models.ImageField(blank=True, null=True, upload_to='paper_drawings/%Y/%m/'),
        ),
    ]
