# Generated by Django 5.1.4 on 2026-09-05 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_paperattempt_drawing'),
        ('syllabus', '0008_syllabusdocument_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.PositiveSmallIntegerField()),
                ('label', models.CharField(max_length=120)),
                ('confidence', models.FloatField(default=0.0)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_topics', to='syllabus.syllabusdocument')),
            ],
            options={
                'ordering': ('document_id', 'page_number'),
                'constraints': [models.UniqueConstraint(fields=('document', 'page_number'), name='unique_topic_per_page')],
            },
        ),
    ]
