# Generated by Django 5.1.4 on 2026-09-11 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_questionanchor_requires_figure_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionanchor',
            name='marking_criteria',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
