# Generated by Django 5.1.4 on 2026-08-30 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0001_initial'),
        ('syllabus', '0004_syllabusdocument_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentchunk',
            name='page_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='DocumentFigure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('ordinal', models.PositiveSmallIntegerField(default=0)),
                ('image', models.ImageField(upload_to='figures/%Y/%m/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='figures', to='syllabus.syllabusdocument')),
            ],
            options={
                'ordering': ('page_number', 'ordinal'),
            },
        ),
    ]
