# Generated by Django 5.1.4 on 2026-09-02 09:29

from django.conf import settings

import pgvector.django.vector
from django.db import migrations


# PostgreSQL-only: create the extension, the vector column and an HNSW index.
# On SQLite this is a no-op (the field is recorded in migration STATE only, so the
# model stays consistent) and the JSON `embedding` path is used instead.
# The column dimension uses settings.EMBEDDING_DIM (default 256 for the hashing
# embedder, 384 for bge-small-en-v1.5) so it always matches the active embedder.


def _dim():
    return getattr(settings, "EMBEDDING_DIM", 256)


def add_pgvector(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    dim = _dim()
    with schema_editor.connection.cursor() as cur:
        cur.execute("CREATE EXTENSION IF NOT EXISTS vector")
        # Idempotent: drop any existing column (so re-running fixes the dimension)
        # then create with the current EMBEDDING_DIM.
        cur.execute("ALTER TABLE rag_documentchunk DROP COLUMN IF EXISTS embedding_vec")
        cur.execute(
            f"ALTER TABLE rag_documentchunk ADD COLUMN embedding_vec vector({dim})"
        )
        cur.execute(
            "CREATE INDEX IF NOT EXISTS docchunk_embedding_vec_hnsw ON rag_documentchunk "
            "USING hnsw (embedding_vec vector_cosine_ops)"
        )


def drop_pgvector(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        with schema_editor.connection.cursor() as cur:
            cur.execute("ALTER TABLE rag_documentchunk DROP COLUMN IF EXISTS embedding_vec")


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0002_documentchunk_page_number_documentfigure'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[migrations.RunPython(add_pgvector, drop_pgvector)],
            state_operations=[
                migrations.AddField(
                    model_name='documentchunk',
                    name='embedding_vec',
                    field=pgvector.django.vector.VectorField(blank=True, null=True),
                ),
            ],
        ),
    ]
