# Generated by Django 5.1.4 on 2026-09-02 09:29

import pgvector.django.vector
from django.db import migrations


# PostgreSQL-only: create the extension, the vector column and an HNSW index.
# On SQLite this is a no-op (the field is recorded in migration STATE only, so the
# model stays consistent) and the JSON `embedding` path is used instead.
# The HNSW index is created by the Python below (not recorded in ORM state, because
# it's a Postgres-only index that the model doesn't declare - avoids drift).
# EMBEDDING_DIM here is 384 (bge-small-en-v1.5); keep in sync with settings.


def add_pgvector(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    with schema_editor.connection.cursor() as cur:
        cur.execute("CREATE EXTENSION IF NOT EXISTS vector")
        cur.execute(
            "ALTER TABLE rag_documentchunk ADD COLUMN embedding_vec vector(384)"
        )
        cur.execute(
            "CREATE INDEX docchunk_embedding_vec_hnsw ON rag_documentchunk "
            "USING hnsw (embedding_vec vector_cosine_ops)"
        )


def drop_pgvector(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        with schema_editor.connection.cursor() as cur:
            cur.execute("ALTER TABLE rag_documentchunk DROP COLUMN embedding_vec")


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0002_documentchunk_page_number_documentfigure'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[migrations.RunPython(add_pgvector, drop_pgvector)],
            state_operations=[
                migrations.AddField(
                    model_name='documentchunk',
                    name='embedding_vec',
                    field=pgvector.django.vector.VectorField(blank=True, null=True),
                ),
            ],
        ),
    ]
