# Generated by Django 5.1.4

from django.conf import settings

import pgvector.django.vector
from django.db import migrations


def _dim():
    return getattr(settings, "EMBEDDING_DIM", 256)


def rebuild_pgvector_column(apps, schema_editor):
    """Recreate the embedding_vec column at the ACTIVE EMBEDDING_DIM.

    The earlier 0003 migration created it as vector(384) hardcoded, but the default
    HashingEmbedder produces EMBEDDING_DIM (256). This drops the column (and its
    HNSW index) and recreates both at the correct dimension, so reembed_chunks can
    write vectors without a dimension mismatch.
    """
    if schema_editor.connection.vendor != "postgresql":
        return
    dim = _dim()
    with schema_editor.connection.cursor() as cur:
        cur.execute("DROP INDEX IF EXISTS docchunk_embedding_vec_hnsw")
        cur.execute("ALTER TABLE rag_documentchunk DROP COLUMN IF EXISTS embedding_vec")
        cur.execute(f"ALTER TABLE rag_documentchunk ADD COLUMN embedding_vec vector({dim})")
        cur.execute(
            "CREATE INDEX docchunk_embedding_vec_hnsw ON rag_documentchunk "
            "USING hnsw (embedding_vec vector_cosine_ops)"
        )


def reverse(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        with schema_editor.connection.cursor() as cur:
            cur.execute("DROP INDEX IF EXISTS docchunk_embedding_vec_hnsw")
            cur.execute("ALTER TABLE rag_documentchunk DROP COLUMN IF EXISTS embedding_vec")


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0003_documentchunk_embedding_vec'),
    ]

    operations = [
        migrations.RunPython(rebuild_pgvector_column, reverse),
    ]