# Generated by Django 5.1.4 on 2026-09-04 21:54

import apps.rag.models
from django.db import migrations, models


def backfill_stable_keys(apps, schema_editor):
    """One-time keys for pre-existing figures (else the unique index fails)."""
    from apps.syllabus.services.figure_keys import figure_key_for

    DocumentFigure = apps.get_model("rag", "DocumentFigure")
    seen = set(
        DocumentFigure.objects.exclude(stable_key="").values_list(
            "stable_key", flat=True)
    )
    rows = list(DocumentFigure.objects.filter(stable_key="").order_by("id"))
    for fig in rows:
        base = figure_key_for(fig.document, fig.page_number, fig.ordinal)
        key, i = base, 2
        while key in seen or DocumentFigure.objects.filter(
                stable_key=key).exists():
            key = f"{base}-{i}"
            i += 1
        fig.stable_key = key
        fig.save(update_fields=["stable_key"])
        seen.add(key)


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0004_rebuild_embedding_vec_dim'),
        ('syllabus', '0008_syllabusdocument_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentfigure',
            name='bbox',
            field=models.JSONField(blank=True, help_text='Region rect [x0, y0, x1, y1] in PDF points; used to match figures across re-ingestions so keys stay stable', null=True),
        ),
        migrations.AddField(
            model_name='documentfigure',
            name='stable_key',
            field=models.CharField(blank=True, default='', help_text='Canonical traceable id, e.g. IGCSE-0580-2024-MJ-P1-p12-f2', max_length=120),
        ),
        migrations.RunPython(backfill_stable_keys, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='documentfigure',
            name='stable_key',
            field=models.CharField(blank=True, default='', help_text='Canonical traceable id, e.g. IGCSE-0580-2024-MJ-P1-p12-f2', max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='documentfigure',
            name='image',
            field=models.ImageField(upload_to=apps.rag.models.figure_upload_to),
        ),
        migrations.AddConstraint(
            model_name='documentfigure',
            constraint=models.UniqueConstraint(fields=('document', 'page_number', 'ordinal'), name='unique_figure_per_page_position'),
        ),
    ]
