# Generated by Django 5.1.4 on 2026-09-02 19:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemoryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fact', models.TextField()),
                ('kind', models.CharField(choices=[('always_on', 'Always-on trait'), ('situational', 'Situational fact')], default='situational', max_length=12)),
                ('importance', models.PositiveSmallIntegerField(default=5)),
                ('embedding', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-importance', '-updated_at'),
            },
        ),
    ]
