# Generated by Django 5.1.4 on 2026-09-02 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0007_learningobjective_code_topic_code_topic_kind_and_more'),
        ('tutoring', '0002_memoryentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='syllabus.topic'),
        ),
    ]
