# Generated by Django 5.1.4 on 2026-08-24 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0002_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='syllabusdocument',
            name='doc_type',
            field=models.CharField(choices=[('syllabus', 'Official syllabus'), ('notes', 'Study notes'), ('past_paper', 'Past exam paper'), ('mark_scheme', 'Mark scheme')], default='notes', max_length=12),
        ),
        migrations.AddField(
            model_name='syllabusdocument',
            name='paper_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='syllabusdocument',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
