# Generated by Django 5.1.4 on 2026-08-29 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0003_syllabusdocument_doc_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='syllabusdocument',
            name='source',
            field=models.CharField(choices=[('igcse', 'Cambridge IGCSE'), ('egcse', 'Eswatini GCSE')], default='egcse', max_length=10),
        ),
    ]
