# Generated by Django 5.1.4 on 2026-08-30 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0004_syllabusdocument_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='tier',
            field=models.CharField(blank=True, choices=[('', 'No tiering'), ('core', 'Core curriculum'), ('extended', 'Extended curriculum')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='subject',
            name='tiers_available',
            field=models.JSONField(blank=True, default=list, help_text='List of tiers, e.g. ["core", "extended"]. Empty = single/un-tiered.'),
        ),
    ]
