# Generated by Django 5.1.4 on 2026-08-30 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0005_enrollment_tier_subject_tiers_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningobjective',
            name='tier',
            field=models.CharField(blank=True, choices=[('', 'No tiering'), ('core', 'Core curriculum'), ('extended', 'Extended curriculum')], default='', max_length=10),
        ),
    ]
