# Generated by Django 5.1.4 on 2026-08-30 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0006_learningobjective_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningobjective',
            name='code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='topic',
            name='code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='topic',
            name='kind',
            field=models.CharField(choices=[('strand', 'Strand'), ('subtopic', 'Subtopic'), ('unknown', 'Unknown')], default='subtopic', max_length=10),
        ),
        migrations.AddField(
            model_name='topic',
            name='topic_areas',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
