# Generated by Django 5.1.4 on 2026-09-04 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0007_learningobjective_code_topic_code_topic_kind_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='syllabusdocument',
            name='session',
            field=models.CharField(blank=True, choices=[('MJ', 'May/June'), ('ON', 'Oct/Nov'), ('FM', 'Feb/March')], default='', help_text='Exam session within the year (parsed from filename when present)', max_length=2),
        ),
    ]
